# Generated by Django 2.1 on 2018-08-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fake',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
